import { tokens as t } from "./theme-contract.css.ts";
export const background = {
  bg_hero: t.background.hero,
  bg_primary: t.background.primary,
  bg_secondary: t.background.secondary,
  bg_tertiary: t.background.tertiary,
  bg_quartenary: t.background.quarternary,
  bg_quinary: t.background.quinary,
  bg_senary: t.background.senary,
  bg_septenary: t.background.septenary,
  bg_octonary: t.background.octonary,
};
export const border = {
  border_primary: t.border.primary,
  border_secondary: t.border.secondary,
  border_tertiary: t.border.tertiary,
  border_quarternary: t.border.quarternary,
  border_quinary: t.border.quinary,
  border_senary: t.border.senary,
};
export const borderRadius = {
  radius_xxs: t.borderRadius.xxs,
  radius_xs: t.borderRadius.xs,
  radius_sm: t.borderRadius.sm,
  radius_md: t.borderRadius.md,
  radius_lg: t.borderRadius.lg,
  radius_xl: t.borderRadius.xl,
  radius_xl1: t.borderRadius.xl1,
  radius_xl2: t.borderRadius.xl2,
};
export const brand = {
  brand_primary: t.brand.primary,
  brand_secondary: t.brand.secondary,
  brand_tertiary: t.brand.tertiary,
  brand_quarternary: t.brand.quarternary,
  brand_quinary: t.brand.quinary,
};
export const button = {
  btn_primary: t.button.primary,
  btn_primary_active: t.button.primary_active,
  btn_primary_text: t.button.primary_text,
  btn_secondary: t.button.secondary,
  btn_secondary_active: t.button.secondary_active,
  btn_secondary_text: t.button.secondary_text,
  btn_tertiary: t.button.tertiary,
  btn_tertiary_active: t.button.tertiary_active,
  btn_tertiary_text: t.button.tertiary_text,
  btn_quarternary: t.button.quarternary,
  btn_quarternary_active: t.button.quarternary_active,
  btn_quarternary_text: t.button.quarternary_text,
  btn_disabled: t.button.disabled,
  btn_disabled_text: t.button.disabled_text,
};
export const drag_handle = {
  drag_handle_brand: t.drag_handle.brand,
  drag_handle_primary: t.drag_handle.primary,
  drag_handle_disabled: t.drag_handle.disabled,
};
export const font = {
  title_display: t.font.title_display,
  title_1: t.font.title_1,
  title_1_meta: t.font.title_1_meta,
  title_2: t.font.title_2,
  title_2_meta: t.font.title_2_meta,
  title_3: t.font.title_3,
  title_4: t.font.title_4,
  title_5: t.font.title_5,
  title_5_meta: t.font.title_5_meta,
  title_6: t.font.title_6,
  title_7: t.font.title_7,
  font_body_1: t.font.body_1,
  font_body_1_strong: t.font.body_1_strong,
  font_body_2: t.font.body_2,
  font_body_2_strong: t.font.body_2_strong,
  font_body_large: t.font.body_large,
  font_body_large_strong: t.font.body_large_strong,
  font_caption_1: t.font.caption_1,
  font_caption_1_strong: t.font.caption_1_strong,
  font_caption_2: t.font.caption_2,
  font_caption_2_strong: t.font.caption_2_strong,
  font_label: t.font.label,
  font_label_small: t.font.label_small,
};
export const icons = {
  icon_brand_background: t.icons.brand_background,
  icon_brand_foreground: t.icons.brand_foreground,
  icon_primary_background: t.icons.primary_background,
  icon_primary_foreground: t.icons.primary_foreground,
  icon_secondary_background: t.icons.secondary_background,
  icon_secondary_foreground: t.icons.secondary_foreground,
  icon_tertiary_background: t.icons.tertiary_background,
  icon_tertiary_foreground: t.icons.tertiary_foreground,
  icon_disabled_background: t.icons.disabled_background,
  icon_disabled_foreground: t.icons.disabled_foreground,
  icon_error_background: t.icons.error_background,
  icon_error_foreground: t.icons.error_foreground,
};
export const pagination = {
  pagination_primary_active: t.pagination.primary_active,
  pagination_primary_inactive: t.pagination.primary_inactive,
  pagination_secondary_active: t.pagination.secondary_active,
  pagination_secondary_inactive: t.pagination.secondary_inactive,
};
export const pill = {
  pill_primary: t.pill.primary,
  pill_primary_text: t.pill.primary_text,
  pill_secondary: t.pill.secondary,
  pill_secondary_text: t.pill.secondary_text,
  pill_tertiary: t.pill.tertiary,
  pill_tertiary_text: t.pill.tertiary_text,
  pill_positive: t.pill.positive,
  pill_negative: t.pill.negative,
};
export const separator = {
  separator_primary: t.separator.primary,
  separator_secondary: t.separator.secondary,
  separator_tertiary: t.separator.tertiary,
  separator_quarternary: t.separator.quarternary,
  separator_quinary: t.separator.quinary,
};
export const skeleton_shimmer = {
  skeleton_shimmer_primary: t.skeleton_shimmer.primary,
  skeleton_shimmer_secondary: t.skeleton_shimmer.secondary,
};
export const spacing = {
  spacing_none: t.spacing.none,
  spacing_xxxs: t.spacing.xxxs,
  spacing_xxs: t.spacing.xxs,
  spacing_xs: t.spacing.xs,
  spacing_sm: t.spacing.sm,
  spacing_md: t.spacing.md,
  spacing_lg: t.spacing.lg,
  spacing_xl: t.spacing.xl,
  spacing_xl1: t.spacing.xl,
  spacing_xl2: t.spacing.xl2,
  spacing_xl3: t.spacing.xl3,
  spacing_xl4: t.spacing.xl4,
  spacing_xl5: t.spacing.xl5,
  spacing_xl6: t.spacing.xl6,
  spacing_xl7: t.spacing.xl7,
  spacing_xl8: t.spacing.xl8,
  spacing_xl9: t.spacing.xl9,
  spacing_xl10: t.spacing.xl10,
  spacing_xl11: t.spacing.xl11,
  spacing_xl12: t.spacing.xl12,
  spacing_xl13: t.spacing.xl13,
  spacing_xl14: t.spacing.xl14,
  spacing_xl15: t.spacing.xl15,
  spacing_xl16: t.spacing.xl16,
  spacing_xl17: t.spacing.xl17,
  spacing_xl18: t.spacing.xl18,
  spacing_xl19: t.spacing.xl19,
  spacing_xl20: t.spacing.xl20,
  spacing_xl21: t.spacing.xl21,
  spacing_xl22: t.spacing.xl22,
  spacing_xl23: t.spacing.xl23,
  spacing_xl24: t.spacing.xl24,
  spacing_xl25: t.spacing.xl25,
  spacing_xl26: t.spacing.xl26,
  spacing_xl27: t.spacing.xl27,
  spacing_xl28: t.spacing.xl28,
  spacing_xl29: t.spacing.xl29,
  spacing_xl30: t.spacing.xl30,
  spacing_xl31: t.spacing.xl31,
};
export const status = {
  status_brand_highlight: t.status.brand_highlight,
  status_error_background: t.status.error_background,
  status_error_primary: t.status.error_primary,
  status_error_secondary: t.status.error_secondary,
  status_info_background: t.status.info_background,
  status_info_primary: t.status.info_primary,
  status_success_background: t.status.success_background,
  status_success_primary: t.status.success_primary,
  status_success_secondary: t.status.success_secondary,
  status_warning_background: t.status.warning_background,
  status_warning_primary: t.status.warning_primary,
  status_warning_secondary: t.status.warning_secondary,
};
export const text = {
  text_primary: t.text.primary,
  text_primary_contrast: t.text.primary_contrast,
  text_secondary: t.text.secondary,
  text_secondary_contrast: t.text.secondary_contrast,
  text_tertiary: t.text.tertiary,
  text_tertiary_contrast: t.text.tertiary_contrast,
  text_link_primary: t.text.link_primary,
  text_link_secondary: t.text.link_secondary,
  text_disabled: t.text.disabled,
  text_error: t.text.error,
};
export const toast = {
  toast_primary: t.toast.primary,
};
