import { createThemeContract } from "@vanilla-extract/css";

export const tokens = createThemeContract({
  background: {
    hero: null,
    primary: null,
    secondary: null,
    tertiary: null,
    quarternary: null,
    quinary: null,
    senary: null,
    septenary: null,
    octonary: null,
  },
  border: {
    primary: null,
    secondary: null,
    tertiary: null,
    quarternary: null,
    quinary: null,
    senary: null,
  },
  borderRadius: {
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xl1: null,
    xl2: null,
  },
  brand: {
    primary: null,
    secondary: null,
    tertiary: null,
    quarternary: null,
    quinary: null,
  },
  button: {
    primary: null,
    primary_active: null,
    primary_text: null,
    secondary: null,
    secondary_active: null,
    secondary_text: null,
    tertiary: null,
    tertiary_active: null,
    tertiary_text: null,
    quarternary: null,
    quarternary_active: null,
    quarternary_text: null,
    disabled: null,
    disabled_text: null,
  },
  drag_handle: {
    brand: null,
    primary: null,
    disabled: null,
  },
  font: {
    title_display: null,
    title_1: null,
    title_1_meta: null,
    title_2: null,
    title_2_meta: null,
    title_3: null,
    title_4: null,
    title_5: null,
    title_5_meta: null,
    title_6: null,
    title_7: null,
    body_1: null,
    body_1_strong: null,
    body_2: null,
    body_2_strong: null,
    body_large: null,
    body_large_strong: null,
    caption_1: null,
    caption_1_strong: null,
    caption_2: null,
    caption_2_strong: null,
    label: null,
    label_small: null,
  },
  icons: {
    brand_background: null,
    brand_foreground: null,
    primary_background: null,
    primary_foreground: null,
    secondary_background: null,
    secondary_foreground: null,
    tertiary_background: null,
    tertiary_foreground: null,
    disabled_background: null,
    disabled_foreground: null,
    error_background: null,
    error_foreground: null,
  },
  pagination: {
    primary_active: null,
    primary_inactive: null,
    secondary_active: null,
    secondary_inactive: null,
  },
  pill: {
    primary: null,
    primary_text: null,
    secondary: null,
    secondary_text: null,
    tertiary: null,
    tertiary_text: null,
    positive: null,
    negative: null,
  },
  separator: {
    primary: null,
    secondary: null,
    tertiary: null,
    quarternary: null,
    quinary: null,
  },
  skeleton_shimmer: {
    primary: null,
    secondary: null,
  },
  spacing: {
    none: null,
    xxxs: null,
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xl1: null,
    xl2: null,
    xl3: null,
    xl4: null,
    xl5: null,
    xl6: null,
    xl7: null,
    xl8: null,
    xl9: null,
    xl10: null,
    xl11: null,
    xl12: null,
    xl13: null,
    xl14: null,
    xl15: null,
    xl16: null,
    xl17: null,
    xl18: null,
    xl19: null,
    xl20: null,
    xl21: null,
    xl22: null,
    xl23: null,
    xl24: null,
    xl25: null,
    xl26: null,
    xl27: null,
    xl28: null,
    xl29: null,
    xl30: null,
    xl31: null,
  },
  status: {
    brand_highlight: null,
    error_background: null,
    error_primary: null,
    error_secondary: null,
    info_background: null,
    info_primary: null,
    success_background: null,
    success_primary: null,
    success_secondary: null,
    warning_background: null,
    warning_primary: null,
    warning_secondary: null,
  },
  toast: {
    primary: null,
  },
  text: {
    primary: null,
    primary_contrast: null,
    secondary: null,
    secondary_contrast: null,
    tertiary: null,
    tertiary_contrast: null,
    link_primary: null,
    link_secondary: null,
    disabled: null,
    error: null,
  },
});
