import { createTheme } from "@vanilla-extract/css";
import { tokens } from "@repo/ui/theme-contract";

export const webTheme = createTheme(tokens, {
  background: {
    hero: "orange",
    primary: "#761c32ff",
    secondary: "#181bb0ff",
    tertiary: "",
    quarternary: "",
    quinary: "",
    senary: "",
    septenary: "",
    octonary: "",
  },
  border: {
    primary: "",
    secondary: "",
    tertiary: "",
    quarternary: "",
    quinary: "",
    senary: "",
  },
  borderRadius: {
    xxs: "",
    xs: "",
    sm: "",
    md: "",
    lg: "",
    xl: "",
    xl1: "",
    xl2: "",
  },
  brand: {
    primary: "",
    secondary: "",
    tertiary: "",
    quarternary: "",
    quinary: "",
  },
  button: {
    primary: "red",
    primary_active: "",
    primary_text: "white",
    secondary: "",
    secondary_active: "",
    secondary_text: "",
    tertiary: "",
    tertiary_active: "",
    tertiary_text: "",
    quarternary: "",
    quarternary_active: "",
    quarternary_text: "",
    disabled: "",
    disabled_text: "",
  },
  drag_handle: {
    brand: "",
    primary: "",
    disabled: "",
  },
  font: {
    title_display: "",
    title_1: "",
    title_1_meta: "",
    title_2: "",
    title_2_meta: "",
    title_3: "",
    title_4: "",
    title_5: "",
    title_5_meta: "",
    title_6: "",
    title_7: "",
    body_1: "",
    body_1_strong: "",
    body_2: "",
    body_2_strong: "",
    body_large: "",
    body_large_strong: "",
    caption_1: "",
    caption_1_strong: "",
    caption_2: "",
    caption_2_strong: "",
    label: "",
    label_small: "",
  },
  icons: {
    brand_background: "",
    brand_foreground: "",
    primary_background: "",
    primary_foreground: "",
    secondary_background: "",
    secondary_foreground: "",
    tertiary_background: "",
    tertiary_foreground: "",
    disabled_background: "",
    disabled_foreground: "",
    error_background: "",
    error_foreground: "",
  },
  pagination: {
    primary_active: "",
    primary_inactive: "",
    secondary_active: "",
    secondary_inactive: "",
  },
  pill: {
    primary: "",
    primary_text: "",
    secondary: "",
    secondary_text: "",
    tertiary: "",
    tertiary_text: "",
    positive: "",
    negative: "",
  },
  separator: {
    primary: "",
    secondary: "",
    tertiary: "",
    quarternary: "",
    quinary: "",
  },
  skeleton_shimmer: {
    primary: "",
    secondary: "",
  },
  spacing: {
    none: "",
    xxxs: "",
    xxs: "",
    xs: "",
    sm: "",
    md: "",
    lg: "",
    xl: "",
    xl1: "",
    xl2: "",
    xl3: "",
    xl4: "",
    xl5: "",
    xl6: "",
    xl7: "",
    xl8: "",
    xl9: "",
    xl10: "",
    xl11: "",
    xl12: "",
    xl13: "",
    xl14: "",
    xl15: "",
    xl16: "",
    xl17: "",
    xl18: "",
    xl19: "",
    xl20: "",
    xl21: "",
    xl22: "",
    xl23: "",
    xl24: "",
    xl25: "",
    xl26: "",
    xl27: "",
    xl28: "",
    xl29: "",
    xl30: "",
    xl31: "",
  },
  status: {
    brand_highlight: "",
    error_background: "",
    error_primary: "",
    error_secondary: "",
    info_background: "",
    info_primary: "",
    success_background: "",
    success_primary: "",
    success_secondary: "",
    warning_background: "",
    warning_primary: "",
    warning_secondary: "",
  },
  toast: {
    primary: "",
  },
  text: {
    primary: "white",
    primary_contrast: "",
    secondary: "black",
    secondary_contrast: "",
    tertiary: "",
    tertiary_contrast: "",
    link_primary: "",
    link_secondary: "",
    disabled: "",
    error: "",
  },
});
